### ISSUE TITLE
Avoid specifying lifetime arguments explicitly

### ISSUE THREAD

**Issue by momvart** [Kobzol/rust-delegate#85]
Consider the following example:
```rust
pub(crate) trait QSet<T>
where
    T: PartialEq,
{
    fn iter<'a>(&'a self) -> impl Iterator<Item = &'a T>
    where
        Self: Sized,
        T: 'a;
}

impl<T: Eq + Hash> QSet<T> for HashSet<T> {
    delegate! {
        to self {
            #[through(HashSet)]
            fn iter<'a>(&'a self) -> impl Iterator<Item = &'a T> + 'a
            where
                Self: Sized,
                T: 'a;
        }
    }
}
```
As the macro tries to pass <'a> to the `iter` function the compiler complains `cannot specify lifetime arguments explicitly if late bound lifetime parameters are present`. If there was a way to tell the macro not to do it, it'd be great. (I know a direct implementation is easier than the delegation but anyway!)

**Comment by Kobzol** [comment]
Hi, thanks for the issue report. Actually, I think that we shouldn't be passing the lifetime arguments, ever (or at least I'm not sure right now if there's a reason to do it).

Could you try if this helps?
```toml
[dependencies]
delegate = { git = "https://github.com/kobzol/rust-delegate", branch = "do-not-forward-lifetime-args" }
```
